import { SearchOutlined } from "@ant-design/icons";
import { Input, Modal, Popover, Tag } from "antd";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import wechatQr from "@/pages/微信.jpg";
import "./index.css";

const products = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "AI 聊天",
    iconDomain: "chatgpt.com",
    spread: 68,
    icon: "https://www.google.com/s2/favicons?domain=chatgpt.com&sz=128",
    regions: [
      {
        rank: 1,
        region: "菲律宾",
        price: "$16.29",
        usd: 16.29,
        unit: "mo",
        local: "≈ ₱999/mo",
        tax: "含 12% 增值税",
        risk: "低",
      },
      {
        rank: 2,
        region: "加拿大",
        price: "$17.61",
        usd: 17.61,
        unit: "mo",
        local: "≈ CA$24.99/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 3,
        region: "巴基斯坦",
        price: "$17.62",
        usd: 17.62,
        unit: "mo",
        local: "≈ Rs4,900/mo",
        tax: "数字服务销售税按省份 15-16% 不同",
        risk: "中",
      },
      {
        rank: 4,
        region: "日本",
        price: "$18.55",
        usd: 18.55,
        unit: "mo",
        local: "≈ ¥3,000/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 5,
        region: "韩国",
        price: "$18.87",
        usd: 18.87,
        unit: "mo",
        local: "≈ ₩29,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 6,
        region: "巴西",
        price: "$19.30",
        usd: 19.3,
        unit: "mo",
        local: "≈ R$99.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "低",
      },
      {
        rank: 7,
        region: "阿根廷",
        price: "$19.99",
        usd: 19.99,
        unit: "mo",
        local: "≈ US$19.99/mo",
        tax: "21% IVA + 8% 数字税",
        risk: "中",
      },
      {
        rank: 8,
        region: "美国",
        price: "$19.99",
        usd: 19.99,
        unit: "mo",
        local: "≈ $19.99/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 9,
        region: "澳大利亚",
        price: "$20.69",
        usd: 20.69,
        unit: "mo",
        local: "≈ A$29.99/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 10,
        region: "印度",
        price: "$21.17",
        usd: 21.17,
        unit: "mo",
        local: "≈ ₹1,999/mo",
        tax: "含 18% GST",
        risk: "低",
      },
      {
        rank: 11,
        region: "土耳其",
        price: "$21.45",
        usd: 21.45,
        unit: "mo",
        local: "≈ ₺999.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 12,
        region: "墨西哥",
        price: "$22.79",
        usd: 22.79,
        unit: "mo",
        local: "≈ MXN399/mo",
        tax: "含 16% IVA",
        risk: "低",
      },
      {
        rank: 13,
        region: "尼日利亚",
        price: "$22.93",
        usd: 22.93,
        unit: "mo",
        local: "≈ ₦31,500/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 14,
        region: "德国",
        price: "$26.18",
        usd: 26.18,
        unit: "mo",
        local: "≈ €22.99/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 15,
        region: "法国",
        price: "$26.18",
        usd: 26.18,
        unit: "mo",
        local: "≈ €22.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "英国",
        price: "$26.39",
        usd: 26.39,
        unit: "mo",
        local: "≈ £19.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 17,
        region: "丹麦",
        price: "$27.32",
        usd: 27.32,
        unit: "mo",
        local: "≈ 179/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "claude",
    name: "Claude",
    category: "AI 聊天",
    iconDomain: "claude.ai",
    spread: 152,
    icon: "https://www.google.com/s2/favicons?domain=claude.ai&sz=128",
    regions: [
      {
        rank: 1,
        region: "尼日利亚",
        price: "$10.85",
        usd: 10.85,
        unit: "mo",
        local: "≈ ₦14,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 2,
        region: "埃及",
        price: "$14.14",
        usd: 14.14,
        unit: "mo",
        local: "≈ E£699.99/mo",
        tax: "含 14% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "土耳其",
        price: "$17.16",
        usd: 17.16,
        unit: "mo",
        local: "≈ ₺799.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 4,
        region: "巴基斯坦",
        price: "$17.62",
        usd: 17.62,
        unit: "mo",
        local: "≈ ₨4,900/mo",
        tax: "数字服务销售税按省份 15-16% 不同",
        risk: "中",
      },
      {
        rank: 5,
        region: "韩国",
        price: "$19.53",
        usd: 19.53,
        unit: "mo",
        local: "≈ ₩30,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 6,
        region: "加拿大",
        price: "$19.74",
        usd: 19.74,
        unit: "mo",
        local: "≈ CA$28/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 7,
        region: "阿根廷",
        price: "$20.00",
        usd: 20,
        unit: "mo",
        local: "≈ US$20/mo",
        tax: "21% IVA + 8% 数字税",
        risk: "中",
      },
      {
        rank: 8,
        region: "美国",
        price: "$20.00",
        usd: 20,
        unit: "mo",
        local: "≈ $20/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 9,
        region: "日本",
        price: "$21.03",
        usd: 21.03,
        unit: "mo",
        local: "≈ ¥3,400/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 10,
        region: "印度",
        price: "$21.17",
        usd: 21.17,
        unit: "mo",
        local: "≈ ₹1,999/mo",
        tax: "含 18% GST",
        risk: "低",
      },
      {
        rank: 11,
        region: "菲律宾",
        price: "$21.20",
        usd: 21.2,
        unit: "mo",
        local: "≈ ₱1,300/mo",
        tax: "含 12% 增值税",
        risk: "低",
      },
      {
        rank: 12,
        region: "巴西",
        price: "$21.23",
        usd: 21.23,
        unit: "mo",
        local: "≈ R$109.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "低",
      },
      {
        rank: 13,
        region: "墨西哥",
        price: "$22.79",
        usd: 22.79,
        unit: "mo",
        local: "≈ MXN399/mo",
        tax: "含 16% IVA",
        risk: "低",
      },
      {
        rank: 14,
        region: "澳大利亚",
        price: "$23.45",
        usd: 23.45,
        unit: "mo",
        local: "≈ A$33.99/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 15,
        region: "德国",
        price: "$25.06",
        usd: 25.06,
        unit: "mo",
        local: "≈ €22/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "法国",
        price: "$25.06",
        usd: 25.06,
        unit: "mo",
        local: "≈ €22/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 17,
        region: "英国",
        price: "$26.41",
        usd: 26.41,
        unit: "mo",
        local: "≈ £20/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 18,
        region: "丹麦",
        price: "$27.32",
        usd: 27.32,
        unit: "mo",
        local: "≈ 179/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "AI 聊天",
    iconDomain: "gemini.google.com",
    spread: 82,
    icon: "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=128",
    regions: [
      {
        rank: 1,
        region: "埃及",
        price: "$14.14",
        usd: 14.14,
        unit: "mo",
        local: "≈ E£699.99/mo",
        tax: "含 14% 增值税",
        risk: "中",
      },
      {
        rank: 2,
        region: "土耳其",
        price: "$15.44",
        usd: 15.44,
        unit: "mo",
        local: "≈ ₺719.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "印度尼西亚",
        price: "$17.26",
        usd: 17.26,
        unit: "mo",
        local: "≈ Rp309,000/mo",
        tax: "含 11% 增值税",
        risk: "中",
      },
      {
        rank: 4,
        region: "日本",
        price: "$17.93",
        usd: 17.93,
        unit: "mo",
        local: "≈ ¥2,900/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 5,
        region: "巴西",
        price: "$18.72",
        usd: 18.72,
        unit: "mo",
        local: "≈ R$96.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "中",
      },
      {
        rank: 6,
        region: "韩国",
        price: "$18.87",
        usd: 18.87,
        unit: "mo",
        local: "≈ ₩29,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 7,
        region: "加拿大",
        price: "$19.02",
        usd: 19.02,
        unit: "mo",
        local: "≈ CA$26.99/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 8,
        region: "美国",
        price: "$19.99",
        usd: 19.99,
        unit: "mo",
        local: "≈ $19.99/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 9,
        region: "印度",
        price: "$20.65",
        usd: 20.65,
        unit: "mo",
        local: "≈ ₹1,950/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 10,
        region: "尼日利亚",
        price: "$20.75",
        usd: 20.75,
        unit: "mo",
        local: "≈ ₦28,500/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 11,
        region: "瑞士",
        price: "$21.00",
        usd: 21,
        unit: "mo",
        local: "≈ CHF17/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 12,
        region: "澳大利亚",
        price: "$22.76",
        usd: 22.76,
        unit: "mo",
        local: "≈ A$32.99/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 13,
        region: "沙特阿拉伯",
        price: "$22.93",
        usd: 22.93,
        unit: "mo",
        local: "≈ SAR85.99/mo",
        tax: "含 15% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "德国",
        price: "$25.05",
        usd: 25.05,
        unit: "mo",
        local: "≈ €21.99/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 15,
        region: "法国",
        price: "$25.05",
        usd: 25.05,
        unit: "mo",
        local: "≈ €21.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "英国",
        price: "$25.07",
        usd: 25.07,
        unit: "mo",
        local: "≈ £18.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 17,
        region: "丹麦",
        price: "$25.80",
        usd: 25.8,
        unit: "mo",
        local: "≈ DKK169/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "grok",
    name: "Grok",
    category: "AI 聊天",
    iconDomain: "x.ai",
    spread: 438,
    icon: "https://www.google.com/s2/favicons?domain=x.ai&sz=128",
    regions: [
      {
        rank: 1,
        region: "印度",
        price: "$7.41",
        usd: 7.41,
        unit: "mo",
        local: "≈ ₹700/mo",
        tax: "含 18% GST",
        risk: "低",
      },
      {
        rank: 2,
        region: "菲律宾",
        price: "$9.77",
        usd: 9.77,
        unit: "mo",
        local: "≈ ₱599/mo",
        tax: "含 12% 增值税",
        risk: "低",
      },
      {
        rank: 3,
        region: "土耳其",
        price: "$27.88",
        usd: 27.88,
        unit: "mo",
        local: "≈ ₺1,299.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 4,
        region: "加拿大",
        price: "$28.19",
        usd: 28.19,
        unit: "mo",
        local: "≈ CA$40/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 5,
        region: "巴基斯坦",
        price: "$28.40",
        usd: 28.4,
        unit: "mo",
        local: "≈ Rs7,900/mo",
        tax: "数字服务销售税按省份 15-16% 不同",
        risk: "中",
      },
      {
        rank: 6,
        region: "韩国",
        price: "$28.64",
        usd: 28.64,
        unit: "mo",
        local: "≈ ₩44,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 7,
        region: "巴西",
        price: "$28.96",
        usd: 28.96,
        unit: "mo",
        local: "≈ R$149.9/mo",
        tax: "各州税率不同",
        risk: "低",
      },
      {
        rank: 8,
        region: "阿根廷",
        price: "$30.00",
        usd: 30,
        unit: "mo",
        local: "≈ US$30/mo",
        tax: "21% IVA + 8% 数字税",
        risk: "中",
      },
      {
        rank: 9,
        region: "美国",
        price: "$30.00",
        usd: 30,
        unit: "mo",
        local: "≈ $30/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 10,
        region: "埃及",
        price: "$30.29",
        usd: 30.29,
        unit: "mo",
        local: "≈ E£1,499.99/mo",
        tax: "含 14% 增值税",
        risk: "中",
      },
      {
        rank: 11,
        region: "日本",
        price: "$30.92",
        usd: 30.92,
        unit: "mo",
        local: "≈ ¥5,000/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 12,
        region: "墨西哥",
        price: "$34.22",
        usd: 34.22,
        unit: "mo",
        local: "≈ MXN599/mo",
        tax: "含 16% IVA",
        risk: "低",
      },
      {
        rank: 13,
        region: "澳大利亚",
        price: "$34.49",
        usd: 34.49,
        unit: "mo",
        local: "≈ A$50/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 14,
        region: "尼日利亚",
        price: "$36.33",
        usd: 36.33,
        unit: "mo",
        local: "≈ ₦49,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 15,
        region: "丹麦",
        price: "$38.01",
        usd: 38.01,
        unit: "mo",
        local: "≈ 249/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "英国",
        price: "$39.61",
        usd: 39.61,
        unit: "mo",
        local: "≈ £30/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 17,
        region: "德国",
        price: "$39.86",
        usd: 39.86,
        unit: "mo",
        local: "≈ €35/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 18,
        region: "法国",
        price: "$39.86",
        usd: 39.86,
        unit: "mo",
        local: "≈ €35/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "glm",
    name: "GLM",
    category: "AI 聊天",
    iconDomain: "chatglm.cn",
    spread: 150,
    icon: "https://www.google.com/s2/favicons?domain=chatglm.cn&sz=128",
    regions: [
      {
        rank: 1,
        region: "中国",
        price: "$7.19",
        usd: 7.19,
        unit: "mo",
        local: "≈ ¥49/mo",
        tax: "含 6% 增值税",
        risk: "中",
      },
      {
        rank: 2,
        region: "加拿大",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 3,
        region: "英国",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 4,
        region: "德国",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 5,
        region: "法国",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 6,
        region: "日本",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 7,
        region: "韩国",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 8,
        region: "印度",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 18% GST",
        risk: "低",
      },
      {
        rank: 9,
        region: "巴西",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "低",
      },
      {
        rank: 10,
        region: "土耳其",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 11,
        region: "墨西哥",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 16% IVA",
        risk: "低",
      },
      {
        rank: 12,
        region: "尼日利亚",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 7.5% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "澳大利亚",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 14,
        region: "巴基斯坦",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "数字服务销售税按省份 15-16% 不同",
        risk: "低",
      },
      {
        rank: 15,
        region: "菲律宾",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "含 12% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "美国",
        price: "$18.00",
        usd: 18,
        unit: "mo",
        local: "≈ US$18/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
    ],
  },
  {
    id: "capcut",
    name: "CapCut",
    category: "视频剪辑",
    iconDomain: "capcut.com",
    spread: 726,
    icon: "https://www.google.com/s2/favicons?domain=capcut.com&sz=128",
    regions: [
      {
        rank: 1,
        region: "印度",
        price: "$4.23",
        usd: 4.23,
        unit: "mo",
        local: "≈ ₹399/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 2,
        region: "印度尼西亚",
        price: "$8.04",
        usd: 8.04,
        unit: "mo",
        local: "≈ Rp144000/mo",
        tax: "含 11% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "土耳其",
        price: "$8.58",
        usd: 8.58,
        unit: "mo",
        local: "≈ ₺399.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 4,
        region: "尼日利亚",
        price: "$10.85",
        usd: 10.85,
        unit: "mo",
        local: "≈ ₦14,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 5,
        region: "巴西",
        price: "$12.73",
        usd: 12.73,
        unit: "mo",
        local: "≈ R$65.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "中",
      },
      {
        rank: 6,
        region: "韩国",
        price: "$12.89",
        usd: 12.89,
        unit: "mo",
        local: "≈ ￦19,800/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 7,
        region: "日本",
        price: "$13.48",
        usd: 13.48,
        unit: "mo",
        local: "≈ ¥2,180/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 8,
        region: "沙特阿拉伯",
        price: "$16.00",
        usd: 16,
        unit: "mo",
        local: "≈ SAR59.99/mo",
        tax: "含 15% 增值税",
        risk: "低",
      },
      {
        rank: 9,
        region: "加拿大",
        price: "$19.73",
        usd: 19.73,
        unit: "mo",
        local: "≈ $27.99/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 10,
        region: "美国",
        price: "$19.99",
        usd: 19.99,
        unit: "mo",
        local: "≈ $19.99/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 11,
        region: "澳大利亚",
        price: "$20.69",
        usd: 20.69,
        unit: "mo",
        local: "≈ $29.99/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 12,
        region: "德国",
        price: "$27.32",
        usd: 27.32,
        unit: "mo",
        local: "≈ €23.99/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "法国",
        price: "$27.32",
        usd: 27.32,
        unit: "mo",
        local: "≈ €23.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "英国",
        price: "$29.03",
        usd: 29.03,
        unit: "mo",
        local: "≈ £21.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 15,
        region: "瑞士",
        price: "$30.88",
        usd: 30.88,
        unit: "mo",
        local: "≈ CHF25/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "丹麦",
        price: "$34.96",
        usd: 34.96,
        unit: "mo",
        local: "≈ 229/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "leonardo-ai",
    name: "Leonardo AI",
    category: "图像生成",
    iconDomain: "leonardo.ai",
    spread: 256,
    icon: "https://www.google.com/s2/favicons?domain=leonardo.ai&sz=128",
    regions: [
      {
        rank: 1,
        region: "尼日利亚",
        price: "$5.75",
        usd: 5.75,
        unit: "mo",
        local: "≈ ₦7,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 2,
        region: "土耳其",
        price: "$8.58",
        usd: 8.58,
        unit: "mo",
        local: "≈ ₺399.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "日本",
        price: "$13.60",
        usd: 13.6,
        unit: "mo",
        local: "≈ ¥2,200/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 4,
        region: "加拿大",
        price: "$14.09",
        usd: 14.09,
        unit: "mo",
        local: "≈ CA$19.99/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 5,
        region: "韩国",
        price: "$14.32",
        usd: 14.32,
        unit: "mo",
        local: "≈ ₩22,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 6,
        region: "巴西",
        price: "$15.44",
        usd: 15.44,
        unit: "mo",
        local: "≈ R$79.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "中",
      },
      {
        rank: 7,
        region: "印度",
        price: "$15.87",
        usd: 15.87,
        unit: "mo",
        local: "≈ ₹1499/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 8,
        region: "美国",
        price: "$15.99",
        usd: 15.99,
        unit: "mo",
        local: "≈ $15.99/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 9,
        region: "印度尼西亚",
        price: "$16.70",
        usd: 16.7,
        unit: "mo",
        local: "≈ Rp299,000/mo",
        tax: "含 11% 增值税",
        risk: "中",
      },
      {
        rank: 10,
        region: "澳大利亚",
        price: "$17.24",
        usd: 17.24,
        unit: "mo",
        local: "≈ A$24.99/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 11,
        region: "瑞士",
        price: "$18.53",
        usd: 18.53,
        unit: "mo",
        local: "≈ CHF15/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 12,
        region: "沙特阿拉伯",
        price: "$18.66",
        usd: 18.66,
        unit: "mo",
        local: "≈ SAR69.99/mo",
        tax: "含 15% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "丹麦",
        price: "$19.69",
        usd: 19.69,
        unit: "mo",
        local: "≈ DKK129/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "英国",
        price: "$19.79",
        usd: 19.79,
        unit: "mo",
        local: "≈ £14.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 15,
        region: "德国",
        price: "$20.49",
        usd: 20.49,
        unit: "mo",
        local: "≈ €17.99/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "法国",
        price: "$20.49",
        usd: 20.49,
        unit: "mo",
        local: "≈ €17.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "character-ai",
    name: "Character.AI",
    category: "角色聊天",
    iconDomain: "character.ai",
    spread: 281,
    icon: "https://www.google.com/s2/favicons?domain=character.ai&sz=128",
    regions: [
      {
        rank: 1,
        region: "尼日利亚",
        price: "$3.57",
        usd: 3.57,
        unit: "mo",
        local: "≈ ₦4,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 2,
        region: "土耳其",
        price: "$5.36",
        usd: 5.36,
        unit: "mo",
        local: "≈ ₺249.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "韩国",
        price: "$9.11",
        usd: 9.11,
        unit: "mo",
        local: "≈ ₩14,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 4,
        region: "加拿大",
        price: "$9.16",
        usd: 9.16,
        unit: "mo",
        local: "≈ CA$12.99/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 5,
        region: "日本",
        price: "$9.28",
        usd: 9.28,
        unit: "mo",
        local: "≈ ¥1,500/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 6,
        region: "印度尼西亚",
        price: "$9.44",
        usd: 9.44,
        unit: "mo",
        local: "≈ Rp169,000/mo",
        tax: "含 11% 增值税",
        risk: "中",
      },
      {
        rank: 7,
        region: "巴西",
        price: "$9.64",
        usd: 9.64,
        unit: "mo",
        local: "≈ R$49.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "中",
      },
      {
        rank: 8,
        region: "美国",
        price: "$9.99",
        usd: 9.99,
        unit: "mo",
        local: "≈ $9.99/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 9,
        region: "澳大利亚",
        price: "$10.34",
        usd: 10.34,
        unit: "mo",
        local: "≈ A$14.99/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 10,
        region: "印度",
        price: "$10.58",
        usd: 10.58,
        unit: "mo",
        local: "≈ ₹999/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 11,
        region: "沙特阿拉伯",
        price: "$10.66",
        usd: 10.66,
        unit: "mo",
        local: "≈ SAR39.99/mo",
        tax: "含 15% 增值税",
        risk: "低",
      },
      {
        rank: 12,
        region: "德国",
        price: "$11.38",
        usd: 11.38,
        unit: "mo",
        local: "≈ €9.99/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "法国",
        price: "$11.38",
        usd: 11.38,
        unit: "mo",
        local: "≈ €9.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "瑞士",
        price: "$12.35",
        usd: 12.35,
        unit: "mo",
        local: "≈ CHF10/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 15,
        region: "英国",
        price: "$13.19",
        usd: 13.19,
        unit: "mo",
        local: "≈ £9.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "丹麦",
        price: "$13.59",
        usd: 13.59,
        unit: "mo",
        local: "≈ DKK89/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "AI 搜索",
    iconDomain: "perplexity.ai",
    spread: 152,
    icon: "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=128",
    regions: [
      {
        rank: 1,
        region: "尼日利亚",
        price: "$10.85",
        usd: 10.85,
        unit: "mo",
        local: "≈ ₦14,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 2,
        region: "土耳其",
        price: "$12.87",
        usd: 12.87,
        unit: "mo",
        local: "≈ ₺599.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "加拿大",
        price: "$17.62",
        usd: 17.62,
        unit: "mo",
        local: "≈ CA$25/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 4,
        region: "日本",
        price: "$18.55",
        usd: 18.55,
        unit: "mo",
        local: "≈ ¥3,000/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 5,
        region: "韩国",
        price: "$18.87",
        usd: 18.87,
        unit: "mo",
        local: "≈ ₩29,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 6,
        region: "巴西",
        price: "$19.30",
        usd: 19.3,
        unit: "mo",
        local: "≈ R$99.9/mo",
        tax: "各州税率不同",
        risk: "中",
      },
      {
        rank: 7,
        region: "美国",
        price: "$20.00",
        usd: 20,
        unit: "mo",
        local: "≈ $20/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 8,
        region: "澳大利亚",
        price: "$20.70",
        usd: 20.7,
        unit: "mo",
        local: "≈ A$30/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 9,
        region: "印度",
        price: "$21.17",
        usd: 21.17,
        unit: "mo",
        local: "≈ ₹1999/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 10,
        region: "瑞士",
        price: "$24.71",
        usd: 24.71,
        unit: "mo",
        local: "≈ CHF 20/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 11,
        region: "法国",
        price: "$25.06",
        usd: 25.06,
        unit: "mo",
        local: "≈ €22/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 12,
        region: "德国",
        price: "$25.06",
        usd: 25.06,
        unit: "mo",
        local: "≈ €22/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "英国",
        price: "$26.41",
        usd: 26.41,
        unit: "mo",
        local: "≈ £20/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "丹麦",
        price: "$27.32",
        usd: 27.32,
        unit: "mo",
        local: "≈ DKK179/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "copilot",
    name: "Microsoft Copilot",
    category: "办公助手",
    iconDomain: "copilot.microsoft.com",
    spread: 110,
    icon: "https://www.google.com/s2/favicons?domain=copilot.microsoft.com&sz=128",
    regions: [
      {
        rank: 1,
        region: "尼日利亚",
        price: "$12.38",
        usd: 12.38,
        unit: "mo",
        local: "≈ ₦17,000/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 2,
        region: "土耳其",
        price: "$15.44",
        usd: 15.44,
        unit: "mo",
        local: "≈ ₺719.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "韩国",
        price: "$18.87",
        usd: 18.87,
        unit: "mo",
        local: "≈ ₩29,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 4,
        region: "加拿大",
        price: "$19.03",
        usd: 19.03,
        unit: "mo",
        local: "≈ CA$27/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 5,
        region: "印度尼西亚",
        price: "$19.49",
        usd: 19.49,
        unit: "mo",
        local: "≈ Rp349,000/mo",
        tax: "含 11% 增值税",
        risk: "中",
      },
      {
        rank: 6,
        region: "日本",
        price: "$19.79",
        usd: 19.79,
        unit: "mo",
        local: "≈ ¥3,200/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 7,
        region: "美国",
        price: "$20.00",
        usd: 20,
        unit: "mo",
        local: "≈ $20/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 8,
        region: "印度",
        price: "$21.18",
        usd: 21.18,
        unit: "mo",
        local: "≈ ₹2,000/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 9,
        region: "巴西",
        price: "$21.23",
        usd: 21.23,
        unit: "mo",
        local: "≈ R$109.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "中",
      },
      {
        rank: 10,
        region: "澳大利亚",
        price: "$22.77",
        usd: 22.77,
        unit: "mo",
        local: "≈ A$33/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 11,
        region: "沙特阿拉伯",
        price: "$22.93",
        usd: 22.93,
        unit: "mo",
        local: "≈ SAR86/mo",
        tax: "含 15% 增值税",
        risk: "低",
      },
      {
        rank: 12,
        region: "德国",
        price: "$25.06",
        usd: 25.06,
        unit: "mo",
        local: "≈ €22/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "法国",
        price: "$25.06",
        usd: 25.06,
        unit: "mo",
        local: "≈ €22/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "英国",
        price: "$25.09",
        usd: 25.09,
        unit: "mo",
        local: "≈ £19/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 15,
        region: "丹麦",
        price: "$25.80",
        usd: 25.8,
        unit: "mo",
        local: "≈ DKK169/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "瑞士",
        price: "$25.94",
        usd: 25.94,
        unit: "mo",
        local: "≈ CHF21/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "manus",
    name: "Manus",
    category: "智能代理",
    iconDomain: "manus.im",
    spread: 54,
    icon: "https://www.google.com/s2/favicons?domain=manus.im&sz=128",
    regions: [
      {
        rank: 1,
        region: "加拿大",
        price: "$34.54",
        usd: 34.54,
        unit: "mo",
        local: "≈ CA$49/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 2,
        region: "韩国",
        price: "$35.80",
        usd: 35.8,
        unit: "mo",
        local: "≈ ₩55,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 3,
        region: "日本",
        price: "$37.10",
        usd: 37.1,
        unit: "mo",
        local: "≈ ¥6,000/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 4,
        region: "土耳其",
        price: "$38.60",
        usd: 38.6,
        unit: "mo",
        local: "≈ ₺1799.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 5,
        region: "美国",
        price: "$39.00",
        usd: 39,
        unit: "mo",
        local: "≈ $39/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 6,
        region: "澳大利亚",
        price: "$40.70",
        usd: 40.7,
        unit: "mo",
        local: "≈ A$59/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 7,
        region: "印度",
        price: "$42.35",
        usd: 42.35,
        unit: "mo",
        local: "≈ ₹3999/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 8,
        region: "尼日利亚",
        price: "$43.61",
        usd: 43.61,
        unit: "mo",
        local: "≈ ₦59,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 9,
        region: "巴西",
        price: "$48.28",
        usd: 48.28,
        unit: "mo",
        local: "≈ R$249.9/mo",
        tax: "各州税率不同",
        risk: "中",
      },
      {
        rank: 10,
        region: "瑞士",
        price: "$49.41",
        usd: 49.41,
        unit: "mo",
        local: "≈ CHF 40/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 11,
        region: "法国",
        price: "$51.25",
        usd: 51.25,
        unit: "mo",
        local: "≈ €45/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 12,
        region: "德国",
        price: "$51.25",
        usd: 51.25,
        unit: "mo",
        local: "≈ €45/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "英国",
        price: "$51.49",
        usd: 51.49,
        unit: "mo",
        local: "≈ £39/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "丹麦",
        price: "$53.28",
        usd: 53.28,
        unit: "mo",
        local: "≈ DKK349/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "kimi",
    name: "Kimi",
    category: "AI 聊天",
    iconDomain: "kimi.moonshot.cn",
    spread: 68,
    icon: "https://www.google.com/s2/favicons?domain=kimi.moonshot.cn&sz=128",
    regions: [
      {
        rank: 1,
        region: "韩国",
        price: "$16.27",
        usd: 16.27,
        unit: "mo",
        local: "≈ ₩25,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 2,
        region: "印度尼西亚",
        price: "$16.70",
        usd: 16.7,
        unit: "mo",
        local: "≈ Rp299,000/mo",
        tax: "含 11% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "土耳其",
        price: "$17.16",
        usd: 17.16,
        unit: "mo",
        local: "≈ ₺799.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 4,
        region: "加拿大",
        price: "$17.62",
        usd: 17.62,
        unit: "mo",
        local: "≈ CA$25/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 5,
        region: "日本",
        price: "$18.55",
        usd: 18.55,
        unit: "mo",
        local: "≈ ¥3,000/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 6,
        region: "美国",
        price: "$19.00",
        usd: 19,
        unit: "mo",
        local: "≈ $19/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 7,
        region: "澳大利亚",
        price: "$20.01",
        usd: 20.01,
        unit: "mo",
        local: "≈ A$29/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 8,
        region: "印度",
        price: "$21.17",
        usd: 21.17,
        unit: "mo",
        local: "≈ ₹1,999/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 9,
        region: "沙特阿拉伯",
        price: "$21.33",
        usd: 21.33,
        unit: "mo",
        local: "≈ SAR79.99/mo",
        tax: "含 15% 增值税",
        risk: "低",
      },
      {
        rank: 10,
        region: "尼日利亚",
        price: "$21.77",
        usd: 21.77,
        unit: "mo",
        local: "≈ ₦29,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 11,
        region: "巴西",
        price: "$23.16",
        usd: 23.16,
        unit: "mo",
        local: "≈ R$119.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "中",
      },
      {
        rank: 12,
        region: "瑞士",
        price: "$24.71",
        usd: 24.71,
        unit: "mo",
        local: "≈ CHF20/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "德国",
        price: "$25.06",
        usd: 25.06,
        unit: "mo",
        local: "≈ €22/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "法国",
        price: "$25.06",
        usd: 25.06,
        unit: "mo",
        local: "≈ €22/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 15,
        region: "英国",
        price: "$25.09",
        usd: 25.09,
        unit: "mo",
        local: "≈ £19/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "丹麦",
        price: "$27.32",
        usd: 27.32,
        unit: "mo",
        local: "≈ DKK179/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "sora",
    name: "Sora",
    category: "视频生成",
    iconDomain: "sora.com",
    spread: 5,
    icon: "https://www.google.com/s2/favicons?domain=sora.com&sz=128",
    regions: [
      {
        rank: 1,
        region: "美国",
        price: "$4.00",
        usd: 4,
        unit: "pack",
        local: "≈ $4.00/pack",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 2,
        region: "韩国",
        price: "$4.10",
        usd: 4.1,
        unit: "pack",
        local: "≈ ₩6,300/pack",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 3,
        region: "日本",
        price: "$4.14",
        usd: 4.14,
        unit: "pack",
        local: "≈ ¥670/pack",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 4,
        region: "加拿大",
        price: "$4.22",
        usd: 4.22,
        unit: "pack",
        local: "≈ CA$5.99/pack",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
    ],
  },
  {
    id: "kling-ai",
    name: "Kling AI",
    category: "视频生成",
    iconDomain: "klingai.com",
    spread: 194,
    icon: "https://www.google.com/s2/favicons?domain=klingai.com&sz=128",
    regions: [
      {
        rank: 1,
        region: "印度",
        price: "$0.52",
        usd: 0.52,
        unit: "mo",
        local: "≈ ₹49/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 2,
        region: "印度尼西亚",
        price: "$1.06",
        usd: 1.06,
        unit: "mo",
        local: "≈ Rp19,000/mo",
        tax: "含 11% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "德国",
        price: "$1.13",
        usd: 1.13,
        unit: "mo",
        local: "≈ €0.99/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 4,
        region: "法国",
        price: "$1.13",
        usd: 1.13,
        unit: "mo",
        local: "≈ €0.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 5,
        region: "美国",
        price: "$1.19",
        usd: 1.19,
        unit: "mo",
        local: "≈ $1.19/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 6,
        region: "瑞士",
        price: "$1.24",
        usd: 1.24,
        unit: "mo",
        local: "≈ CHF1/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 7,
        region: "日本",
        price: "$1.24",
        usd: 1.24,
        unit: "mo",
        local: "≈ ¥200/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 8,
        region: "土耳其",
        price: "$1.29",
        usd: 1.29,
        unit: "mo",
        local: "≈ ₺59.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 9,
        region: "英国",
        price: "$1.31",
        usd: 1.31,
        unit: "mo",
        local: "≈ £0.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 10,
        region: "沙特阿拉伯",
        price: "$1.33",
        usd: 1.33,
        unit: "mo",
        local: "≈ SAR4.99/mo",
        tax: "含 15% 增值税",
        risk: "低",
      },
      {
        rank: 11,
        region: "丹麦",
        price: "$1.37",
        usd: 1.37,
        unit: "mo",
        local: "≈ DKK9/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
      {
        rank: 12,
        region: "澳大利亚",
        price: "$1.37",
        usd: 1.37,
        unit: "mo",
        local: "≈ A$1.99/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 13,
        region: "尼日利亚",
        price: "$1.38",
        usd: 1.38,
        unit: "mo",
        local: "≈ ₦1,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 14,
        region: "加拿大",
        price: "$1.40",
        usd: 1.4,
        unit: "mo",
        local: "≈ CA$1.99/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 15,
        region: "韩国",
        price: "$1.43",
        usd: 1.43,
        unit: "mo",
        local: "≈ ₩2,200/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "巴西",
        price: "$1.53",
        usd: 1.53,
        unit: "mo",
        local: "≈ R$7.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "中",
      },
    ],
  },
  {
    id: "catcosplay",
    name: "CatCosplay",
    category: "图像生成",
    iconDomain: "catcosplay.ai",
    spread: 49,
    icon: "https://www.google.com/s2/favicons?domain=catcosplay.ai&sz=128",
    regions: [
      {
        rank: 1,
        region: "美国",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 2,
        region: "加拿大",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 3,
        region: "英国",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 4,
        region: "德国",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 5,
        region: "法国",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 6,
        region: "日本",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 7,
        region: "韩国",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 8,
        region: "印度",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 18% GST",
        risk: "低",
      },
      {
        rank: 9,
        region: "巴西",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "低",
      },
      {
        rank: 10,
        region: "土耳其",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 11,
        region: "墨西哥",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 16% IVA",
        risk: "低",
      },
      {
        rank: 12,
        region: "尼日利亚",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 7.5% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "澳大利亚",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 14,
        region: "巴基斯坦",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "数字服务销售税按省份 15-16% 不同",
        risk: "低",
      },
      {
        rank: 15,
        region: "菲律宾",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 12% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "中国",
        price: "$18.99",
        usd: 18.99,
        unit: "mo",
        local: "≈ US$18.99/mo",
        tax: "含 6% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "suno",
    name: "Suno",
    category: "音乐生成",
    iconDomain: "suno.com",
    spread: 49,
    icon: "https://www.google.com/s2/favicons?domain=suno.com&sz=128",
    regions: [
      {
        rank: 1,
        region: "韩国",
        price: "$9.11",
        usd: 9.11,
        unit: "mo",
        local: "≈ ₩14,000/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 2,
        region: "日本",
        price: "$9.28",
        usd: 9.28,
        unit: "mo",
        local: "≈ ¥1,500/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 3,
        region: "印度尼西亚",
        price: "$9.44",
        usd: 9.44,
        unit: "mo",
        local: "≈ Rp169,000/mo",
        tax: "含 11% 增值税",
        risk: "中",
      },
      {
        rank: 4,
        region: "加拿大",
        price: "$9.87",
        usd: 9.87,
        unit: "mo",
        local: "≈ CA$14/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 5,
        region: "美国",
        price: "$10.00",
        usd: 10,
        unit: "mo",
        local: "≈ $10/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 6,
        region: "澳大利亚",
        price: "$10.35",
        usd: 10.35,
        unit: "mo",
        local: "≈ A$15/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 7,
        region: "印度",
        price: "$10.58",
        usd: 10.58,
        unit: "mo",
        local: "≈ ₹999/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 8,
        region: "沙特阿拉伯",
        price: "$10.66",
        usd: 10.66,
        unit: "mo",
        local: "≈ SAR39.99/mo",
        tax: "含 15% 增值税",
        risk: "低",
      },
      {
        rank: 9,
        region: "土耳其",
        price: "$10.72",
        usd: 10.72,
        unit: "mo",
        local: "≈ ₺499.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 10,
        region: "尼日利亚",
        price: "$10.85",
        usd: 10.85,
        unit: "mo",
        local: "≈ ₦14,900/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 11,
        region: "瑞士",
        price: "$11.12",
        usd: 11.12,
        unit: "mo",
        local: "≈ CHF9/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 12,
        region: "德国",
        price: "$11.39",
        usd: 11.39,
        unit: "mo",
        local: "≈ €10/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 13,
        region: "法国",
        price: "$11.39",
        usd: 11.39,
        unit: "mo",
        local: "≈ €10/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "巴西",
        price: "$11.57",
        usd: 11.57,
        unit: "mo",
        local: "≈ R$59.9/mo",
        tax: "州税（ICMS）7-25% 不同",
        risk: "中",
      },
      {
        rank: 15,
        region: "英国",
        price: "$13.20",
        usd: 13.2,
        unit: "mo",
        local: "≈ £10/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "丹麦",
        price: "$13.59",
        usd: 13.59,
        unit: "mo",
        local: "≈ DKK89/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
    ],
  },
  {
    id: "x",
    name: "X",
    category: "社交平台",
    iconDomain: "x.com",
    spread: 396,
    icon: "https://www.google.com/s2/favicons?domain=x.com&sz=128",
    regions: [
      {
        rank: 1,
        region: "韩国",
        price: "$2.93",
        usd: 2.93,
        unit: "mo",
        local: "≈ ₩4,500/mo",
        tax: "含 10% 增值税",
        risk: "低",
      },
      {
        rank: 2,
        region: "土耳其",
        price: "$4.29",
        usd: 4.29,
        unit: "mo",
        local: "≈ ₺199.99/mo",
        tax: "含 20% 增值税",
        risk: "中",
      },
      {
        rank: 3,
        region: "印度",
        price: "$4.98",
        usd: 4.98,
        unit: "mo",
        local: "≈ ₹470/mo",
        tax: "含 18% GST",
        risk: "中",
      },
      {
        rank: 4,
        region: "阿根廷",
        price: "$5.00",
        usd: 5,
        unit: "mo",
        local: "≈ US$5/mo",
        tax: "含 21% 增值税；礼品卡税额可能不同",
        risk: "中",
      },
      {
        rank: 5,
        region: "巴基斯坦",
        price: "$5.03",
        usd: 5.03,
        unit: "mo",
        local: "≈ Rs1,400/mo",
        tax: "数字服务销售税按省份 15-16% 不同",
        risk: "中",
      },
      {
        rank: 6,
        region: "埃及",
        price: "$5.05",
        usd: 5.05,
        unit: "mo",
        local: "≈ EGP 250/mo",
        tax: "含 14% 增值税",
        risk: "中",
      },
      {
        rank: 7,
        region: "尼日利亚",
        price: "$5.53",
        usd: 5.53,
        unit: "mo",
        local: "≈ ₦7,600/mo",
        tax: "含 7.5% 增值税",
        risk: "中",
      },
      {
        rank: 8,
        region: "巴西",
        price: "$6.18",
        usd: 6.18,
        unit: "mo",
        local: "≈ R$32/mo",
        tax: "各州税率不同；无全国统一增值税",
        risk: "低",
      },
      {
        rank: 9,
        region: "日本",
        price: "$7.85",
        usd: 7.85,
        unit: "mo",
        local: "≈ ¥1,270/mo",
        tax: "含 10% 消费税",
        risk: "低",
      },
      {
        rank: 10,
        region: "加拿大",
        price: "$9.87",
        usd: 9.87,
        unit: "mo",
        local: "≈ CA$14/mo",
        tax: "各省 5-15% GST/HST 不同",
        risk: "低",
      },
      {
        rank: 11,
        region: "美国",
        price: "$11.00",
        usd: 11,
        unit: "mo",
        local: "≈ $11/mo",
        tax: "各州销售税 0-10% 不同",
        risk: "低",
      },
      {
        rank: 12,
        region: "澳大利亚",
        price: "$11.04",
        usd: 11.04,
        unit: "mo",
        local: "≈ A$16/mo",
        tax: "含 10% GST",
        risk: "低",
      },
      {
        rank: 13,
        region: "丹麦",
        price: "$11.75",
        usd: 11.75,
        unit: "mo",
        local: "≈ 77/mo",
        tax: "含 25% 增值税",
        risk: "低",
      },
      {
        rank: 14,
        region: "瑞士",
        price: "$12.35",
        usd: 12.35,
        unit: "mo",
        local: "≈ CHF10/mo",
        tax: "含 8.1% 增值税",
        risk: "低",
      },
      {
        rank: 15,
        region: "德国",
        price: "$12.53",
        usd: 12.53,
        unit: "mo",
        local: "≈ €11/mo",
        tax: "含 19% 增值税",
        risk: "低",
      },
      {
        rank: 16,
        region: "法国",
        price: "$12.53",
        usd: 12.53,
        unit: "mo",
        local: "≈ €11/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
      {
        rank: 17,
        region: "英国",
        price: "$14.52",
        usd: 14.52,
        unit: "mo",
        local: "≈ £11/mo",
        tax: "含 20% 增值税",
        risk: "低",
      },
    ],
  },
];

const formatUsd = (value, unit = "mo") =>
  `$${value.toFixed(value % 1 === 0 ? 0 : 2)}/${unit}`;
const formatPrice = (region) =>
  region.price || formatUsd(region.usd, region.unit);
const getIconUrl = (domain) =>
  `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
const getProductMark = (product) =>
  product.name
    .split(/[\s.]+/)
    .map((item) => item[0])
    .join("")
    .slice(0, 2);

function ProductIcon({ product, className = "" }) {
  const mark = getProductMark(product);

  return (
    <span
      className={["ai-pricing-product-mark", className]
        .filter(Boolean)
        .join(" ")}
    >
      <img
        alt={`${product.name} 图标`}
        src={getIconUrl(product.iconDomain)}
        onError={(event) => {
          event.currentTarget.classList.add("is-hidden");
        }}
      />
      <span>{mark}</span>
    </span>
  );
}

function WechatContact() {
  return (
    <div className="ai-pricing-wechat-card">
      <img alt="微信二维码" src={wechatQr} />
      <strong>添加我的微信</strong>
      <span>扫码联系，咨询账号、VPN 和 AI 订阅办理</span>
    </div>
  );
}

const serviceNotes = [
  { label: "设备评估", value: "最好是 Mac 电脑" },
  { label: "VPN 办理", value: "40 元 / 月" },
  { label: "Google 账号", value: "15 元 / 个" },
  { label: "ChatGPT 办理", value: "120 元 / 月" },
];

export default function AiPricing() {
  const [keyword, setKeyword] = useState("");
  const [serviceModalOpen, setServiceModalOpen] = useState(false);

  const filteredProducts = useMemo(() => {
    const normalizedKeyword = keyword.trim().toLowerCase();
    return products.filter((item) => {
      const regionText = item.regions.map((region) => region.region).join(" ");
      const matchKeyword =
        !normalizedKeyword ||
        item.name.toLowerCase().includes(normalizedKeyword) ||
        item.category.toLowerCase().includes(normalizedKeyword) ||
        regionText.includes(normalizedKeyword);
      return matchKeyword;
    });
  }, [keyword]);

  return (
    <div className="ai-pricing-page">
      <header className="ai-pricing-header">
        <Link className="ai-pricing-logo" to="/ai-pricing">
          <span>AI</span>
          Pricing
        </Link>
        <nav className="ai-pricing-nav">
          <button
            className="ai-pricing-nav-label"
            type="button"
            onClick={() => setServiceModalOpen(true)}
          >
            办理价格
          </button>
          <Popover
            arrow={false}
            content={<WechatContact />}
            overlayClassName="ai-pricing-contact-popover"
            placement="bottomRight"
            trigger="click"
          >
            <button className="ai-pricing-contact-button" type="button">
              联系我
            </button>
          </Popover>
        </nav>
      </header>

      <main className="ai-pricing-main">
        <section className="ai-pricing-toolbar">
          <Input
            allowClear
            className="ai-pricing-search"
            placeholder="搜索产品、地区或办理类型"
            prefix={<SearchOutlined />}
            value={keyword}
            onChange={(event) => setKeyword(event.target.value)}
          />
        </section>

        <section className="ai-pricing-grid" id="products">
          {filteredProducts.map((product, productIndex) => {
            const lowest = product.regions[0];
            return (
              <article
                className="ai-pricing-card"
                key={product.name}
                style={{ "--card-index": productIndex }}
              >
                <div className="ai-pricing-card-head">
                  <div className="ai-pricing-product-title">
                    <ProductIcon product={product} />
                    <div>
                      <h2>{product.name}</h2>
                      <span>{product.category}</span>
                    </div>
                  </div>
                  <Tag color="blue">价差 {product.spread}%</Tag>
                </div>

                <div className="ai-pricing-lowest">
                  <span>最低办理价</span>
                  <strong>{formatPrice(lowest)}</strong>
                  <em>{lowest.region}</em>
                </div>

                <ol className="ai-pricing-region-list">
                  {product.regions.map((region, index) => (
                    <li key={`${product.name}-${region.region}`}>
                      <span className="ai-pricing-rank">{index + 1}</span>
                      <span className="ai-pricing-region-name">
                        {region.region}
                      </span>
                      <strong>{formatPrice(region)}</strong>
                      <span className="ai-pricing-local">
                        {[region.local, region.tax].filter(Boolean).join(" · ")}
                      </span>
                    </li>
                  ))}
                </ol>
              </article>
            );
          })}
        </section>
      </main>

      <Modal
        centered
        footer={null}
        open={serviceModalOpen}
        title={null}
        width={720}
        onCancel={() => setServiceModalOpen(false)}
        className="ai-pricing-service-modal"
      >
        <section
          className="ai-pricing-service-panel"
          aria-label="办理前提和参考价格"
        >
          <div className="ai-pricing-service-list">
            {serviceNotes.map((item) => (
              <div className="ai-pricing-service-item" key={item.label}>
                <span>{item.label}</span>
                <strong>{item.value}</strong>
              </div>
            ))}
          </div>
        </section>
      </Modal>
    </div>
  );
}
