export const initialSuggestionTasks = [
  {
    id: "SUG-001",
    directorName: "张铁斌",
    type: "经营管理类",
    content: "建议持续跟踪重点项目收益及经营风险指标。",
    source: "能源科技经营情况专题调研",
    owner: "股权运营部",
    assignee: "陈哲",
    deadline: "2026-10-30",
    progress: 20,
    status: "待办理",
    handlingPlan: "建立重点项目月度跟踪清单，明确收益和风险预警指标。",
    result: "",
    feedback: "",
    files: [],
  },
  {
    id: "SUG-002",
    directorName: "张铁斌",
    type: "战略规划类",
    content: "明确研发中心技术路线，评估智能网联领域资本投向。",
    source: "第二次董事会",
    owner: "投资部",
    assignee: "孙博",
    deadline: "2026-10-20",
    progress: 65,
    status: "办理中",
    handlingPlan: "完成行业对标和投资收益测算，形成资本投向建议稿。",
    result: "已完成行业对标，正在开展重点项目收益测算。",
    feedback: "",
    files: ["智能网联领域行业对标材料.pdf"],
  },
  {
    id: "SUG-003",
    directorName: "张铁斌",
    type: "风险防控类",
    content: "平衡内部控制数字化的管控范围与执行效率。",
    source: "内部控制议题",
    owner: "审计风控与法务部",
    assignee: "王珂",
    deadline: "2026-09-30",
    progress: 100,
    status: "已完成",
    handlingPlan: "梳理关键控制点并完成数字化流程分级。",
    result: "已形成分级管控清单和流程优化方案。",
    feedback: "董事已查看办理成果，同意归档。",
    files: ["内控数字化分级管控清单.xlsx", "流程优化方案.pdf"],
    completedAt: "2026-09-28 16:20",
  },
];
