export const confirmationOwners = [
  "张铁斌",
  "李晨光",
  "王珂",
  "阮迪",
  "胡欣悦",
];

export const initialDutyPlans = [
  {
    id: "PLAN-001",
    directorName: "张铁斌",
    servingCompany: "一汽能源科技公司",
    dutyYear: "2026年",
    dutyQuarter: "三季度",
    type: "会议计划",
    workCategory: "参加董事会",
    content: "第四次定期董事会",
    owner: "综合管理部-董办",
    confirmOwner: "张铁斌",
    date: "2026-12-16",
    target: "完成重点议题审议并形成会议成果",
    status: "已完成",
    confirmationNote: "计划内容及时间安排已确认。",
    confirmedAt: "2026-09-15 14:20",
    taskStatus: "待执行",
    taskAssignee: "阮迪",
    actualDate: "2026-12-16",
    completionSummary:
      "已完成第四次定期董事会会务组织、议题材料归集及会议纪要整理。",
    evidenceNote: "会议通知、议题材料、会议纪要及决议清单已归档。",
    supplementFiles: ["第四次定期董事会会议纪要.pdf", "董事会决议清单.xlsx"],
  },
  {
    id: "PLAN-002",
    directorName: "张铁斌",
    servingCompany: "一汽能源科技公司",
    dutyYear: "2026年",
    dutyQuarter: "三季度",
    type: "培训计划",
    workCategory: "参加能力培训",
    content: "参股企业风险与合规培训",
    owner: "综合管理部-人力",
    confirmOwner: "张铁斌",
    date: "2026-10-22",
    target: "完成培训并归集学习材料",
    status: "已完成",
    confirmationNote: "培训主题、时间及成果要求已确认。",
    confirmedAt: "2026-09-15 14:35",
    taskStatus: "办理中",
    taskAssignee: "周航",
    actualDate: "2026-10-22",
    completionSummary:
      "已完成风险与合规专题培训，参训人员签到、课件及学习反馈已汇总。",
    evidenceNote: "培训课件、签到表、培训总结及学习反馈已归档。",
    supplementFiles: ["风险与合规培训课件.pdf", "培训签到及反馈汇总.xlsx"],
  },
  {
    id: "PLAN-003",
    directorName: "张铁斌",
    servingCompany: "一汽能源科技公司",
    dutyYear: "2026年",
    dutyQuarter: "三季度",
    type: "调研计划",
    workCategory: "参加调研",
    content: "能源科技经营情况专题调研",
    owner: "股权运营部",
    confirmOwner: "张铁斌",
    date: "2026-10-15",
    target: "形成专题调研报告及建议清单",
    status: "已完成",
    confirmationNote: "调研对象、计划时间及成果要求已确认。",
    confirmedAt: "2026-09-15 14:48",
    taskStatus: "已完成",
    taskAssignee: "陈哲",
    actualDate: "2026-10-15",
    completionSummary:
      "已完成能源科技经营情况专题调研，归集经营数据并形成专题调研报告。",
    resultSuggestion: "建议持续跟踪重点项目收益及经营风险指标。",
    evidenceNote: "专题调研报告和建议清单已归档。",
    supplementFiles: ["能源科技经营情况专题调研报告.pdf", "调研建议清单.xlsx"],
    taskCompletedAt: "2026-10-15 16:30",
  },
];
