export const initialDutyReports = [
  {
    id: "REPORT-M-202609",
    directorName: "张铁斌",
    company: "一汽能源科技公司",
    reportType: "月度报告",
    period: "2026年9月",
    title: "2026年9月张铁斌履职写实报告",
    status: "已接收",
    sourceCount: 2,
    sourcePlanIds: ["PLAN-001", "PLAN-003"],
    generatedAt: "2026-09-30 09:30",
    receivedAt: "2026-10-02 14:10",
    summary: "围绕董事会审议准备和能源科技经营调研开展履职工作。",
    workHighlights:
      "1. 完成董事会议题审阅。\n2. 完成能源科技经营情况专题调研。",
    suggestions: "建议持续跟踪重点项目收益及经营风险指标。",
    files: ["2026年9月履职写实报告.pdf"],
  },
  {
    id: "REPORT-Q-2026Q3",
    directorName: "张铁斌",
    company: "一汽能源科技公司",
    reportType: "季度报告",
    period: "2026年第三季度",
    title: "2026年第三季度张铁斌履职写实报告",
    status: "待完善",
    sourceCount: 3,
    sourcePlanIds: ["PLAN-001", "PLAN-002", "PLAN-003"],
    generatedAt: "2026-10-08 10:00",
    summary: "系统已归集第三季度会议、培训和调研履职事实。",
    workHighlights:
      "1. 参加董事会。\n2. 参加风险与合规培训。\n3. 开展专题调研。",
    suggestions: "需补充季度重点建议的后续安排。",
    files: [],
  },
  {
    id: "REPORT-Y-2026",
    directorName: "张铁斌",
    company: "一汽能源科技公司",
    reportType: "年度报告",
    period: "2026年度",
    title: "2026年度张铁斌履职报告",
    status: "待接收",
    sourceCount: 8,
    sourcePlanIds: ["PLAN-001", "PLAN-002", "PLAN-003"],
    generatedAt: "2026-12-20 09:00",
    submittedAt: "2026-12-21 15:40",
    summary: "年度履职报告已完成编制并提交董办接收。",
    workHighlights: "围绕战略决策、风险防控和经营改善履行董事职责。",
    suggestions: "持续完善重点项目投后评价机制。",
    files: ["2026年度履职报告.docx"],
  },
];
