export const initialSuggestionTasks = [
  {
    id: "SUG-001",
    directorName: "张铁斌",
    type: "经营管理类",
    content: "建议持续跟踪重点项目收益及经营风险指标。",
    source: "能源科技经营情况专题调研",
    sourceTaskId: "PLAN-003",
    sourceTaskSnapshot: {
      id: "PLAN-003",
      content: "能源科技经营情况专题调研",
      type: "调研计划",
      date: "2026-10-15",
    },
    initiatorRole: "director",
    initiatorName: "张铁斌",
    owner: "股权运营部",
    assignee: "陈哲",
    deadline: "2026-10-30",
    progress: 20,
    status: "办理中",
    handlingPlan: "建立重点项目月度跟踪清单，明确收益和风险预警指标。",
    result: "",
    feedback: "",
    files: [],
    createdAt: "2026-10-15 16:35",
    dispatchedAt: "2026-10-16 09:20",
    history: [
      { action: "发起建议", actor: "张铁斌", at: "2026-10-15 16:35" },
      { action: "下发建议", actor: "综合管理部-董办", at: "2026-10-16 09:20" },
      { action: "保存进展", actor: "陈哲", at: "2026-10-17 14:10" },
    ],
  },
  {
    id: "SUG-002",
    directorName: "张铁斌",
    type: "战略规划类",
    content: "建议明确能源科技研发中心技术路线，评估智能网联领域资本投向。",
    source: "能源科技经营情况专题调研",
    sourceTaskId: "PLAN-003",
    sourceTaskSnapshot: {
      id: "PLAN-003",
      content: "能源科技经营情况专题调研",
      type: "调研计划",
      date: "2026-10-15",
    },
    initiatorRole: "director",
    initiatorName: "张铁斌",
    owner: "",
    assignee: "",
    deadline: "",
    progress: 0,
    status: "待董办补充",
    handlingPlan: "",
    result: "",
    feedback: "",
    files: [],
    createdAt: "2026-10-08 09:30",
    history: [{ action: "发起建议", actor: "张铁斌", at: "2026-10-08 09:30" }],
  },
  {
    id: "SUG-003",
    directorName: "张铁斌",
    type: "风险防控类",
    content: "平衡内部控制数字化的管控范围与执行效率。",
    source: "内部控制议题",
    legacySource: true,
    initiatorRole: "director",
    initiatorName: "张铁斌",
    owner: "审计风控与法务部",
    assignee: "王珂",
    deadline: "2026-09-30",
    progress: 100,
    status: "已关闭",
    handlingPlan: "梳理关键控制点并完成数字化流程分级。",
    result: "已形成分级管控清单和流程优化方案。",
    feedback: "董事已查看办理成果，同意归档。",
    files: ["内控数字化分级管控清单.xlsx", "流程优化方案.pdf"],
    completedAt: "2026-09-28 16:20",
    createdAt: "2026-09-20 10:00",
    dispatchedAt: "2026-09-21 09:00",
    history: [
      { action: "发起建议", actor: "张铁斌", at: "2026-09-20 10:00" },
      { action: "下发建议", actor: "综合管理部-董办", at: "2026-09-21 09:00" },
      { action: "关闭建议", actor: "王珂", at: "2026-09-28 16:20" },
    ],
  },
];
