export const handbookMaterials = [
  {
    id: "HB-01",
    category: "战略规划",
    material: "“531”规划",
    department: "综合管理部-办公室",
    responsiblePerson: "胡欣悦",
    frequency: "年度",
    status: "已提交",
  },
  {
    id: "HB-02",
    category: "公司简介",
    material: "公司基本情况介绍",
    department: "综合管理部-办公室",
    responsiblePerson: "阮迪",
    frequency: "季度",
    status: "已提交",
  },
  {
    id: "HB-03",
    category: "业务资料",
    material: "股权运营核心业务材料（一口清、一企一策、参股企业介绍）",
    department: "股权运营部",
    responsiblePerson: "待业务部门指定",
    frequency: "季度",
    status: "已提交",
  },
  {
    id: "HB-04",
    category: "业务资料",
    material: "产业投资核心业务材料（投资研究报告、在管项目基本情况）",
    department: "投资部",
    responsiblePerson: "待业务部门指定",
    frequency: "季度",
    status: "已提交",
  },
  {
    id: "HB-05",
    category: "支撑机制",
    material: "公司系统功能介绍",
    department: "综合管理部-数字化",
    responsiblePerson: "待职能部门指定",
    frequency: "季度",
    status: "已提交",
  },
  {
    id: "HB-06",
    category: "支撑机制",
    material: "外部董事履职服务支撑机制",
    department: "综合管理部-办公室",
    responsiblePerson: "阮迪",
    frequency: "年度",
    status: "已提交",
  },
  {
    id: "HB-07",
    category: "制度文件",
    material: "公司治理相关制度文件",
    department: "综合管理部-办公室",
    responsiblePerson: "阮迪",
    frequency: "年度",
    status: "已提交",
  },
  {
    id: "HB-08",
    category: "其他",
    material: "其他",
    department: "综合管理部-办公室",
    responsiblePerson: "阮迪",
    frequency: "季度",
    status: "已提交",
  },
];

export const handbookDepartments = [
  "综合管理部-办公室",
  "股权运营部",
  "投资部",
  "综合管理部-数字化",
];
