import {
  AuditOutlined,
  CalendarOutlined,
  CheckSquareOutlined,
  DashboardOutlined,
  SendOutlined,
  SettingOutlined,
  SolutionOutlined,
  TeamOutlined,
} from "@ant-design/icons";

export const navigationItems = [
  { key: "home", label: "工作台首页", icon: DashboardOutlined },
  { key: "appointment", label: "董事聘任", icon: SolutionOutlined },
  {
    key: "director-special-tasks",
    label: "下发董事专项任务",
    icon: SendOutlined,
  },
  { key: "preparation", label: "履职准备", icon: CalendarOutlined },
  { key: "management", label: "履职管理", icon: TeamOutlined },
  { key: "duty-evaluation", label: "履职评价", icon: AuditOutlined },
  { key: "duty-tasks", label: "履职任务", icon: CheckSquareOutlined },
  { key: "roles", label: "履职角色配置", icon: SettingOutlined },
];

export const metrics = [
  {
    label: "年度治理计划完成率",
    value: "88%",
    trend: "较上月 +6%",
    tone: "blue",
  },
  {
    label: "董事履职计划达成率",
    value: "92%",
    trend: "18 项待确认",
    tone: "cyan",
  },
  { label: "决议执行闭环率", value: "85%", trend: "3 项临期", tone: "green" },
  { label: "治理偏差闭环率", value: "76%", trend: "2 项已逾期", tone: "amber" },
];

export const tasks = [
  {
    id: "T-101",
    title: "确认四季度董事履职计划",
    module: "董事履职",
    company: "一汽股权",
    deadline: "今天 17:00",
    status: "待确认",
    risk: "urgent",
  },
  {
    id: "T-102",
    title: "补充第三次定期董事会材料",
    module: "会议管理",
    company: "一汽股权",
    deadline: "09-16",
    status: "待补充",
    risk: "warning",
  },
  {
    id: "T-103",
    title: "审核旗新动力决议执行进展",
    module: "治理监控",
    company: "旗新动力",
    deadline: "09-18",
    status: "待审核",
    risk: "normal",
  },
  {
    id: "T-104",
    title: "更新股权运营核心业务材料",
    module: "治理资料",
    company: "一汽股权",
    deadline: "09-20",
    status: "待提交",
    risk: "normal",
  },
  {
    id: "T-105",
    title: "处理董事建议落实反馈",
    module: "治理监控",
    company: "能源科技",
    deadline: "已逾期 2 天",
    status: "办理中",
    risk: "danger",
  },
];

export const schedules = [
  {
    date: "09/18",
    time: "09:00",
    title: "第三次定期董事会材料预审",
    type: "会议",
    location: "线上",
  },
  {
    date: "09/22",
    time: "14:00",
    title: "参股企业经营情况专题调研",
    type: "调研",
    location: "会议中心 301",
  },
  {
    date: "09/26",
    time: "13:30",
    title: "公司治理与风险防控培训",
    type: "培训",
    location: "云课堂",
  },
];

export const plans = [
  {
    id: "P-2026-01",
    name: "2026 年董事会治理重点任务",
    type: "治理重点任务",
    company: "一汽股权",
    owner: "综合管理部",
    progress: 86,
    status: "执行中",
    risk: "正常",
    milestone: "制度修订与运行评价",
  },
  {
    id: "P-2026-02",
    name: "2026 年度董事会会议计划",
    type: "年度会议计划",
    company: "一汽股权",
    owner: "公司董办",
    progress: 75,
    status: "执行中",
    risk: "正常",
    milestone: "第四次定期会议",
  },
  {
    id: "P-2026-03",
    name: "张铁斌董事四季度履职计划",
    type: "董事履职计划",
    company: "一汽股权",
    owner: "阮迪",
    progress: 20,
    status: "待确认",
    risk: "临期",
    milestone: "董事确认",
  },
  {
    id: "P-2026-04",
    name: "旗新动力董事会运行计划",
    type: "子企业运行计划",
    company: "旗新动力",
    owner: "子企业董办",
    progress: 68,
    status: "执行中",
    risk: "1 项偏差",
    milestone: "三季度运行督导",
  },
];

export const meetingStages = [
  "会议计划",
  "议题征集",
  "议题审核",
  "通知与材料",
  "会前沟通",
  "会议召开",
  "表决与决议",
  "任务落实",
  "会议归档",
];

export const meetings = [
  {
    id: "M-2026-04",
    name: "2026 年第四次定期董事会",
    date: "2026-12-16",
    stage: "议题征集",
    topics: 10,
    readiness: 42,
    readRate: 0,
    status: "筹备中",
  },
  {
    id: "M-2026-03",
    name: "2026 年第三次定期董事会",
    date: "2026-09-28",
    stage: "通知与材料",
    topics: 8,
    readiness: 83,
    readRate: 62,
    status: "材料准备中",
  },
  {
    id: "M-2026-02",
    name: "2026 年第二次董事会",
    date: "2026-03-25",
    stage: "会议归档",
    topics: 13,
    readiness: 100,
    readRate: 100,
    status: "已完成",
  },
];

export const topics = [
  {
    id: "A-01",
    name: "2026 年经营情况及 2027 年经营预算方案",
    department: "计划财务部",
    kind: "审议",
    material: "已提交",
    review: "合规审核中",
    opinions: 3,
    decision: "待表决",
  },
  {
    id: "A-02",
    name: "董事会决议执行情况报告",
    department: "综合管理部",
    kind: "听取",
    material: "最终版",
    review: "已通过",
    opinions: 1,
    decision: "待表决",
  },
  {
    id: "A-03",
    name: "2027 年重大风险评估报告",
    department: "审计风控与法务部",
    kind: "审议",
    material: "待补充",
    review: "待提交",
    opinions: 0,
    decision: "待表决",
  },
];

export const directors = [
  {
    id: "D-01",
    name: "张铁斌",
    role: "外部董事召集人",
    company: "一汽股权",
    term: "2026-01-01 至 2028-12-31",
    committee: "战略委员会主任委员",
    days: 15.5,
    completion: 92,
    report: "待确认",
    risk: "正常",
    lifecycleStage: "management",
    appointmentStatus: "已完成",
    preparationStatus: "已完成",
    managementStatus: "执行中",
    evaluationStatus: "待确认",
  },
  {
    id: "D-02",
    name: "李晨光",
    role: "专职外部董事",
    company: "一汽股权",
    term: "2025-06-01 至 2028-05-31",
    committee: "审计与风险委员会委员",
    days: 13,
    completion: 81,
    report: "待补充",
    risk: "履职缺口",
    lifecycleStage: "preparation",
    appointmentStatus: "已完成",
    preparationStatus: "待补充",
    managementStatus: "待生成任务",
    evaluationStatus: "未开始",
  },
  {
    id: "D-03",
    name: "王珂",
    role: "外部董事",
    company: "一汽股权",
    term: "2025-01-01 至 2027-12-31",
    committee: "提名委员会委员",
    days: 12.5,
    completion: 88,
    report: "已提交",
    risk: "正常",
    lifecycleStage: "management",
    appointmentStatus: "已完成",
    preparationStatus: "已完成",
    managementStatus: "已完成",
    evaluationStatus: "已完成",
  },
  {
    id: "D-05",
    name: "陈思远",
    role: "专职外部董事",
    company: "旗新动力科技",
    term: "2026-06-01 至 2029-05-31",
    committee: "审计与风险委员会委员",
    days: 3.5,
    completion: 24,
    report: "未开始",
    risk: "正常",
    lifecycleStage: "appointment",
    appointmentStatus: "待上传董事简历",
    preparationStatus: "未开始",
    managementStatus: "未开始",
    evaluationStatus: "未开始",
  },
  {
    id: "D-06",
    name: "林舒然",
    role: "外部董事",
    company: "红旗私募基金",
    term: "2025-10-01 至 2028-09-30",
    committee: "提名委员会委员",
    days: 8,
    completion: 67,
    report: "待确认",
    risk: "正常",
    lifecycleStage: "appointment",
    appointmentStatus: "待配置系统权限",
    preparationStatus: "未开始",
    managementStatus: "未开始",
    evaluationStatus: "未开始",
  },
  {
    id: "D-07",
    name: "许知远",
    role: "外部董事",
    company: "一汽资本控股",
    term: "2026-08-01 至 2029-07-31",
    committee: "审计与风险委员会委员",
    days: 0,
    completion: 0,
    report: "未开始",
    risk: "临期",
    lifecycleStage: "appointment",
    appointmentStatus: "待完成工商变更",
    preparationStatus: "未开始",
    managementStatus: "未开始",
    evaluationStatus: "未开始",
  },
  {
    id: "D-08",
    name: "刘欣然",
    role: "外部董事",
    company: "一汽智行科技",
    term: "2026-03-01 至 2029-02-28",
    committee: "战略委员会委员",
    days: 4,
    completion: 36,
    report: "未开始",
    risk: "正常",
    lifecycleStage: "preparation",
    appointmentStatus: "已完成",
    preparationStatus: "确认中",
    managementStatus: "待生成任务",
    evaluationStatus: "未开始",
  },
  {
    id: "D-10",
    name: "周明轩",
    role: "外部董事",
    company: "一汽新材料科技",
    term: "2026-05-01 至 2029-04-30",
    committee: "提名委员会委员",
    days: 0,
    completion: 0,
    report: "未开始",
    risk: "正常",
    lifecycleStage: "appointment",
    appointmentStatus: "待完成工商变更",
    preparationStatus: "未开始",
    managementStatus: "未开始",
    evaluationStatus: "未开始",
  },
  {
    id: "D-09",
    name: "何向东",
    role: "专职外部董事",
    company: "一汽供应链科技",
    term: "2025-07-01 至 2028-06-30",
    committee: "提名委员会委员",
    days: 10.5,
    completion: 72,
    report: "待确认",
    risk: "正常",
    lifecycleStage: "management",
    appointmentStatus: "已完成",
    preparationStatus: "已完成",
    managementStatus: "待确认",
    evaluationStatus: "评价中",
  },
];

export const dutyEvents = [
  {
    id: "E-01",
    date: "2026-03-25",
    title: "一汽股权 2026 年董事会第二次会议",
    type: "董事会参会决策",
    source: "系统同步",
    status: "已确认",
    days: 4,
    evidence: "13 项议案、7 条意见建议",
  },
  {
    id: "E-02",
    date: "2026-01-29",
    title: "战略规划与数字化建设专题调研",
    type: "调查研究",
    source: "董办填报",
    status: "已确认",
    days: 0.5,
    evidence: "现场调研，未形成调研报告",
  },
  {
    id: "E-03",
    date: "2026-09-08",
    title: "参股企业财务风险处置培训",
    type: "履职能力培训",
    source: "人事培训同步",
    status: "待董事确认",
    days: 0.5,
    evidence: "视频课程 3 小时",
  },
  {
    id: "E-04",
    date: "2026-09-12",
    title: "531 规划专项交流",
    type: "专项交流沟通",
    source: "助理补充",
    status: "待检查",
    days: 0.5,
    evidence: "形成 2 条规划建议",
  },
];

export const suggestions = [
  {
    id: "S-01",
    type: "战略规划类",
    content: "明确研发中心技术路线，评估集团智能网联领域资本投向。",
    source: "第二次董事会",
    owner: "投资部",
    deadline: "2026-10-20",
    progress: 65,
    status: "办理中",
  },
  {
    id: "S-02",
    type: "风险防控类",
    content: "平衡内部控制数字化的管控范围与执行效率。",
    source: "内部控制议题",
    owner: "审计风控与法务部",
    deadline: "2026-09-30",
    progress: 90,
    status: "待确认",
  },
  {
    id: "S-03",
    type: "经营管理类",
    content: "补充半年度高级管理人员绩效指标，保持评价口径一致。",
    source: "薪酬议题",
    owner: "人力资源部",
    deadline: "2026-09-10",
    progress: 55,
    status: "已逾期",
  },
];

export const companies = [
  {
    id: "C-01",
    name: "一汽股权",
    level: "二级全资",
    seats: "7 / 7",
    external: 4,
    vacancy: 0,
    meetings: "3 / 4",
    closure: 85,
    score: 92,
    risk: "正常",
  },
  {
    id: "C-02",
    name: "一汽能源科技",
    level: "三级控股",
    seats: "6 / 7",
    external: 3,
    vacancy: 1,
    meetings: "4 / 5",
    closure: 78,
    score: 84,
    risk: "席位空缺",
  },
  {
    id: "C-03",
    name: "旗新动力科技",
    level: "三级控股",
    seats: "7 / 7",
    external: 4,
    vacancy: 0,
    meetings: "6 / 7",
    closure: 71,
    score: 81,
    risk: "2 项偏差",
  },
  {
    id: "C-04",
    name: "红旗私募基金",
    level: "三级全资",
    seats: "5 / 5",
    external: 3,
    vacancy: 0,
    meetings: "3 / 3",
    closure: 96,
    score: 95,
    risk: "正常",
  },
];

export const monitoringItems = [
  {
    id: "G-01",
    type: "决议执行",
    title: "完成旗新动力股权划转实施方案",
    company: "一汽股权",
    owner: "股权运营部 / 赵明",
    deadline: "2026-10-15",
    progress: 72,
    stage: "办理中",
    risk: "临期",
  },
  {
    id: "G-02",
    type: "授权执行",
    title: "董事会授权总经理事项季度点检",
    company: "一汽股权",
    owner: "综合管理部 / 阮迪",
    deadline: "2026-09-30",
    progress: 90,
    stage: "待审批",
    risk: "正常",
  },
  {
    id: "G-03",
    type: "董事建议落实",
    title: "完善内部控制数字化边界方案",
    company: "一汽股权",
    owner: "审计风控与法务部 / 孙妍",
    deadline: "2026-09-13",
    progress: 55,
    stage: "办理中",
    risk: "已逾期",
  },
  {
    id: "G-04",
    type: "治理改进",
    title: "补齐能源科技董事席位",
    company: "一汽能源科技",
    owner: "人力资源部 / 周航",
    deadline: "2026-11-01",
    progress: 35,
    stage: "办理中",
    risk: "正常",
  },
];

export const evaluationItems = [
  {
    id: "EV-01",
    object: "一汽股权董事会",
    type: "企业董事会评价",
    model: "2026 董事会建设评价模型 V2",
    progress: 76,
    score: 91.6,
    stage: "过程评价",
    evidence: "38 / 42 项完整",
  },
  {
    id: "EV-02",
    object: "张铁斌",
    type: "董事履职评价",
    model: "2026 外部董事履职模型 V3",
    progress: 82,
    score: 93.2,
    stage: "年度评价",
    evidence: "26 / 28 项完整",
  },
  {
    id: "EV-03",
    object: "旗新动力科技董事会",
    type: "企业董事会评价",
    model: "2026 董事会建设评价模型 V2",
    progress: 63,
    score: 81.4,
    stage: "待审核",
    evidence: "31 / 42 项完整",
  },
];

export const resources = [
  {
    id: "R-01",
    category: "战略规划",
    name: "“531”规划",
    owner: "综合管理部-办公室 / 胡欣悦",
    frequency: "年度",
    updated: "2026-01-12",
    next: "2027-01-10",
    source: "人工维护",
    status: "有效",
    level: "内部",
  },
  {
    id: "R-02",
    category: "公司简介",
    name: "公司基本情况介绍",
    owner: "综合管理部-办公室 / 阮迪",
    frequency: "季度",
    updated: "2026-07-05",
    next: "2026-10-05",
    source: "系统直取",
    status: "临期更新",
    level: "内部",
  },
  {
    id: "R-03",
    category: "业务资料",
    name: "股权运营核心业务材料",
    owner: "股权运营部 / 李琳",
    frequency: "季度",
    updated: "2026-06-30",
    next: "2026-09-30",
    source: "资料包",
    status: "待提交",
    level: "秘密",
  },
  {
    id: "R-04",
    category: "业务资料",
    name: "产业投资核心业务材料",
    owner: "投资部 / 陈哲",
    frequency: "季度",
    updated: "2026-09-10",
    next: "2026-12-10",
    source: "系统直取",
    status: "有效",
    level: "秘密",
  },
  {
    id: "R-05",
    category: "制度文件",
    name: "公司治理相关制度文件",
    owner: "综合管理部-办公室 / 阮迪",
    frequency: "年度",
    updated: "2026-02-18",
    next: "2027-02-18",
    source: "OA 同步",
    status: "有效",
    level: "内部",
  },
];
